homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
    path('profile/', views.aboutMe, name='aboutMe'),
	path('skills/', views.mySkills, name='mySkills'),
	path('projects/', views.myProjects, name='myProjects'),
	path('form/', views.form, name='form'),
	path('testform/', views.testform, name='testform'),
	path('myfriend/', views.myfriend, name='myfriend'),
]

yafia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models
from django.forms import ModelForm

class ClassYear(models.Model):
    BATCH_CHOICES= [('2019 (Maung)', '2019 (Maung)'),
    ('2018 (Quanta)', '2018 (Quanta)'),
    ('2017 (Tarung)', '2017 (Tarung)'),
    ('2016 (Omega)', '2016 (Omega)'),
    ('Others', 'Others')]
    batch = models.CharField(max_length=255, choices=BATCH_CHOICES, default='NULL')

    def __str__(self):
        return self.batch


class Friend(models.Model):
	name = models.CharField(max_length=30)
	hobby = models.CharField(max_length=30)
	favoriteFood = models.CharField(max_length=30)
	favoriteDrink = models.CharField(max_length=30)
	year = models.ForeignKey(ClassYear, on_delete=models.CASCADE)
	
	def __str__(self):
		return self.name

homepage/forms.py
from django import forms
from .models import Friend, ClassYear

class FriendForm(forms.ModelForm):
    
    class Meta:
        model = Friend
        fields = ['name', 
        'year', 
        'hobby', 
        'favoriteFood', 
        'favoriteDrink']
        labels = {'name': 'Name',
        'year': 'Batch',
        'hobby': 'Hobby',
        'favoriteFood': 'Favorite Food',
        'favoriteDrink': 'Favorite Drink',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

homepage/views.py
from django.shortcuts import render
from .models import Friend, ClassYear
from django.shortcuts import redirect
from . import forms

# Create your views here.
def home(request):
    return render(request, 'home bootstrap.html')
	
def aboutMe(request):
    return render(request, 'About me bootstrap.html')

def mySkills(request):
    return render(request, 'My Skills bootstrap.html')
	
def myProjects(request):
    return render(request, 'My Projects bootstrap.html')
	
def form(request):
	return render(request, 'form.html')
	
def testform(request):
    if request.method == 'POST':
        form = forms.FriendForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('homepage:myfriend')
    else:
        form = forms.FriendForm()
    return render(request, 'testform.html', {'form': form})

def myfriend(request):
    allFriend = Friend.objects.all()
    year = ClassYear.objects.all()
    response = {'allFriend' : allFriend, 'year': year}
    return render(request, 'myfriend.html', response)

homepage/templates/About me bootstrap.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <title>About Me.</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet'>
  <link href='https://fonts.googleapis.com/css?family=Saira Extra Condensed' rel='stylesheet'>
  <link href='https://fonts.googleapis.com/css?family=Bad Script' rel='stylesheet'>
  <link href='https://fonts.googleapis.com/css?family=Josefin Sans' rel='stylesheet'>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body style="overflow-x:hidden;">
	
	<!--Header-->
	<nav class="navbar navbar-default" style="width:100%; margin-bottom:0px ;border: 0px;">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>                        
				</button>
			<a class="navbar-brand logo" href="#">Yafia.</a>
			</div>
			<div class="collapse navbar-collapse" id="myNavbar">
				<ul class="nav navbar-nav">
					<li class="nav-btn"><a href="{% url 'homepage:home' %}">Home</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:aboutMe' %}">Profile</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:mySkills' %}">Skills</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:myProjects' %}">Projects</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:testform' %}">Form</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:myfriend' %}">My Friends</a></li>
				</ul>
			</div>
		</div>
	</nav>
	
	<!--About Me. Section-->
	<div class="container-xl home" id="home2" style="overflow-x:hidden; padding:0; margin-top:0; width:100%; height:auto;">
		<div class="col-sm-7 section">
			<h5 id="title2">About Me.</h5>
			<img src="{% static 'about me photo.jpg' %}" id="photo" alt="photo">
		</div>
		<div class="col-sm-5 section">
			<p id="homeText2">
				Hello!, my name is Yafi Ahsan Hakim,<br>
				i’m currently a student at the University of <br>
				Indonesia. I’m studying computer science to <br>
				become a profesional programmer in the<br>
				future. I like to spend my free time by <br>
				watching some interesting videos on the <br>
				internet.	
			</p>
		</div>
	</div>
	
	
	<!--My Social Media. Section-->
	<div class="container-xl" style="overflow-x:hidden; padding:0; margin-top:0;">
		<div class="col-sm-8 section" id="socialMediaLeft">
			<div class="col-sm-1" style="margin-left:15vw; margin-top:16vh;">
				<a href="https://twitter.com/PlotadYafi">
					<img src="{% static 'twitter.png' %}" class="linkImage" alt="twitter">
				</a>
				<a href="https://www.instagram.com/yafiahakim/">
					<img src="{% static 'instagram.png' %}" class="linkImage" alt="instagram">
				</a>
				<a href="http://steamcommunity.com/id/PlotadYafi/">
					<img src="{% static 'steam.png' %}" class="linkImage" alt="steam">
				</a>
			</div>
			<div class="col-sm-4" id="textLink">
				<a href="https://twitter.com/PlotadYafi"><p class="linkText" style="margin-top:17vh;">Twitter: @PlotadYafi</p></a>
				<a href="https://www.instagram.com/yafiahakim/"><p class="linkText">Instagram: @yafiahakim</p></a>
				<a href="http://steamcommunity.com/id/PlotadYafi/"><p class="linkText">Steam: PlotadYafi</p></a>
			</div>				
		</div>
		<div class="col-sm-4 section">
			<br>
			<br>
			<hr style="border-top: 0.5vh solid grey;">
			<h1 id="title2">My <br>Social <br>Media.</h1>
			<hr style="border-top: 0.5vh solid grey;">
		</div>
	</div>

	<!--Footer-->
	<nav class="navbar navbar-default" style="width:100%; margin-bottom:0px ;border: 0px;">
		<div class="container-fluid" id="footer">
			
			<a class="navbar-brand logo" href="#">Yafia.</a>
			
			<div class="collapse navbar-collapse" id="myNavbar">
				<ul class="nav navbar-nav">
					<li class="nav-btn"><a href="{% url 'homepage:home' %}">Home</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:aboutMe' %}">Profile</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:mySkills' %}">Skills</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:myProjects' %}">Projects</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:testform' %}">Form</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:myfriend' %}">My Friends</a></li>
				</ul>
			</div>
		</div>
	</nav>
	
	<!--Challenge-->
	{% include 'copyright.html' %}
</body>
</html>

homepage/templates/My Projects bootstrap.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <title>My Projects.</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet'>
  <link href='https://fonts.googleapis.com/css?family=Saira Extra Condensed' rel='stylesheet'>
  <link href='https://fonts.googleapis.com/css?family=Josefin Sans' rel='stylesheet'>
  <link href='https://fonts.googleapis.com/css?family=Bungee' rel='stylesheet'>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body style="overflow-x:hidden;">
	
	<!--Header-->
	<nav class="navbar navbar-default" style="width:100%; margin-bottom:0px ;border: 0px;">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>                        
				</button>
			<a class="navbar-brand logo" href="#">Yafia.</a>
			</div>
			<div class="collapse navbar-collapse" id="myNavbar">
				<ul class="nav navbar-nav">
					<li class="nav-btn"><a href="{% url 'homepage:home' %}">Home</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:aboutMe' %}">Profile</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:mySkills' %}">Skills</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:myProjects' %}">Projects</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:testform' %}">Form</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:myfriend' %}">My Friends</a></li>
				</ul>
			</div>
		</div>
	</nav>
	
	<!--Home-->
	<div class="container-xl home" id="home4" style="overflow-x:hidden; padding:0; margin-top:0; width:100vw; height:100vh;">
		<h5 id="title4">My Project.</h5>
		<p id="homeText4">
			If you're a fellow computer science student <br>
			and are interested in some of my project, <br>
			below is where you can find the links to the <br>
			gitlab repository of some of my projects. <br>
			Feel free to look at them!
		</p>
	</div>
	
	<!--Top Projects Section-->
	<div class="container-xl" style="overflow-x:hidden; padding:0; margin-top:0;">
		<!--The Art of Git Section-->
		<div class="col-sm-6 section" style="background-color:#FEE58C; height:70vh">	
			<h1 class="ProjectName" style="padding-top:0;">The Art of git</h1>	
			<p id="SectionText4">
				This project contains step-by-step tutorial on how to use Git. <br>
				this project is perfect for those who want to <br>
				learn how to use git.
			</p>
			<a href="https://gitlab.com/YafiAhsanHakim/the-art-of-git.git">
				<button class="btn" id="TheArtOfGit">Gitlab Repository</button>
			</a>
		</div>
		<!--Adprog Tutorial Section-->
		<div class="col-sm-6 section" style="background-color:#92CAFF; height:70vh">
			<h1 class="ProjectName" style="padding-top:0;">Adprog Tutorial</h1>
			<p id="SectionText4">
				This project contains exercises about advanced programming <br>
				that i have been taking. you can definitely increase your <br>
				programming skills if you do this exercises!
			</p>
			<a href="https://gitlab.com/YafiAhsanHakim/adprog-tutorial.git">
				<button class="btn" id="AdprogTutorial">Gitlab Repository</button>
			</a>
		</div>
	</div>
	
	<!--Bot Projects Section-->
	<div class="container-xl" style="overflow-x:hidden; padding:0; margin-top:0;">
		<!--PPWLab1 Section-->
		<div class="col-sm-6 section" style="background-color:#95FF9F; height:70vh">
			<h1 class="ProjectName" style="padding-top:0; margin-left:15vw">PPWLab1</h1>
			<p id="SectionText4">
				In this project, you can learn how to develop your own website <br>
				using html and css language. 
			</p>
			<a href="https://gitlab.com/YafiAhsanHakim/ppwlab1.git">
				<button class="btn" id="PPWLab1">Gitlab Repository</button>
			</a>
		</div>
		<!--Coming Soon... Section-->
		<div class="col-sm-6 section" style="background-color:#FF8585; height:70vh">
			<h1 class="ProjectName" style="margin-left:10vw; padding-top:21vh; font-size:4vw;">COMING SOON...</h1>
		</div>
	</div>

	<!--Footer-->
	<nav class="navbar navbar-default" style="width:100%; margin-bottom:0px ;border: 0px;">
		<div class="container-fluid" id="footer">
			
			<a class="navbar-brand logo" href="#">Yafia.</a>
			
			<div class="collapse navbar-collapse" id="myNavbar">
				<ul class="nav navbar-nav">
					<li class="nav-btn"><a href="{% url 'homepage:home' %}">Home</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:aboutMe' %}">Profile</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:mySkills' %}">Skills</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:myProjects' %}">Projects</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:testform' %}">Form</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:myfriend' %}">My Friends</a></li>
				</ul>
			</div>
		</div>
	</nav>
	
	<!--Challenge-->
	{% include 'copyright.html' %}
</body>
</html>

homepage/templates/My Skills bootstrap.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <title>My Skills.</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet'>
  <link href='https://fonts.googleapis.com/css?family=Saira Extra Condensed' rel='stylesheet'>
  <link href='https://fonts.googleapis.com/css?family=Bad Script' rel='stylesheet'>
  <link href='https://fonts.googleapis.com/css?family=Josefin Sans' rel='stylesheet'>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body style="overflow-x:hidden;">
	
	<!--Header-->
	<nav class="navbar navbar-default" style="width:100%; margin-bottom:0px ;border: 0px;">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>                        
				</button>
			<a class="navbar-brand logo" href="#">Yafia.</a>
			</div>
			<div class="collapse navbar-collapse" id="myNavbar">
				<ul class="nav navbar-nav">
					<li class="nav-btn"><a href="{% url 'homepage:home' %}">Home</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:aboutMe' %}">Profile</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:mySkills' %}">Skills</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:myProjects' %}">Projects</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:testform' %}">Form</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:myfriend' %}">My Friends</a></li>
				</ul>
			</div>
		</div>
	</nav>
	
	<!--My Skills. Section-->
	<div class="container-xl home" id="home3" style="overflow-x:hidden; padding:0; margin-top:0; width:100%; height:110vh;">
		<h5 id="title3">My Skills.</h5>
		<p id="homeText3">
			I’ve studied <b>programming</b> using <br>
			both <b>python language</b> <br>
			and <b>java language.</b> <br>
			<b>Making a website</b> using <br>
			<b>HTML language</b> is no problem for me. <br>
			I can also <b>create a database</b> using <br>
			<b>postgreSQL.</b>
		</p>
	</div>
	
	<!--Footer-->
	<nav class="navbar navbar-default" style="width:100%; margin-bottom:0px ;border: 0px;">
		<div class="container-fluid" id="footer">
			
			<a class="navbar-brand logo" href="#">Yafia.</a>
			
			<div class="collapse navbar-collapse" id="myNavbar">
				<ul class="nav navbar-nav">
					<li class="nav-btn"><a href="{% url 'homepage:home' %}">Home</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:aboutMe' %}">Profile</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:mySkills' %}">Skills</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:myProjects' %}">Projects</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:testform' %}">Form</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:myfriend' %}">My Friends</a></li>
				</ul>
			</div>
		</div>
	</nav>
	
	<!--Challenge-->
	{% include 'copyright.html' %}
</body>
</html>

homepage/templates/copyright.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <title>My Projects.</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet'>
  <link href='https://fonts.googleapis.com/css?family=Saira Extra Condensed' rel='stylesheet'>
  <link href='https://fonts.googleapis.com/css?family=Josefin Sans' rel='stylesheet'>
  <link href='https://fonts.googleapis.com/css?family=Bungee' rel='stylesheet'>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
	<div class="col-sm-12" style="background-color:#F0F0F0; border-top: 0.4px solid #BDBDBD; bottom:0;">
		<h1 id="copyright">@Copyright</h1>
	</div>
</body>
</html>

homepage/templates/home bootstrap.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <title>Yafia.</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet'>
  <link href='https://fonts.googleapis.com/css?family=Saira Extra Condensed' rel='stylesheet'>
  <link href='https://fonts.googleapis.com/css?family=Bad Script' rel='stylesheet'>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body style="overflow-x:hidden;">
	
	<!--Header-->
	<nav class="navbar navbar-default" style="width:100%; margin-bottom:0px ;border: 0px;">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>                        
				</button>
			<a class="navbar-brand logo" href="#">Yafia.</a>
			</div>
			<div class="collapse navbar-collapse" id="myNavbar">
				<ul class="nav navbar-nav">
					<li class="nav-btn"><a href="{% url 'homepage:home' %}">Home</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:aboutMe' %}">Profile</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:mySkills' %}">Skills</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:myProjects' %}">Projects</a></li>
					<li class="nav-btn" data-toggle="modal" data-target="#myModal"><a>Modal</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:testform' %}">Form</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:myfriend' %}">My Friends</a></li>
				</ul>
			</div>
		</div>
	</nav>
	
	<!--Home-->
	<div class="container-xl home" id="home1" style="overflow-x:hidden; padding:0; margin-top:0; width:100%">
		<h5 id="title1">This Is My <br>Personal <br>Website.</h5>
	</div>
	
	<!--About Me. Section-->
	<div class="container-xl" style="overflow-x:hidden; padding:0; margin-top:0;">
		<div class="col-sm-6 section" style="background-color:#C8FFE4;">
			<h1 class="SectionHeading" style="padding-top:0;">ABOUT ME.</h1>
			<p id="SectionText1">
				If you are interested in knowing more about <br>
				me, consider clicking this button to <br>
				see my profile.
			</p>
			<a href="{% url 'homepage:aboutMe' %}">
				<button class="btn" id="profile">Profile</button>
			</a>
		</div>
		<div class="col-sm-6 section" style="background-color:#000000;">
			<img src="{% static 'user (1).png' %}" class="icon" alt="profile">
		</div>
	</div>
	
	<!--My Skills. Section-->
	<div class="container-xl" style="overflow-x:hidden; padding:0; margin-top:0;">
		<div class="col-sm-6 section" style="background-color:#000000;">
			<img src="{% static 'edu & skills.png' %}" class="icon" alt="skills">
		</div>
		<div class="col-sm-6 section" style="background-color:#F8FFCA;">
			<h1 class="SectionHeading" style="padding-top:0;">MY SKILLS.</h1>
			<p id="SectionText1">
				Look at what skills i have learned <br>
				as a programmer here. If you’re interested, <br>
				consider hiring me to work on your projects.
			</p>
			<a href="{% url 'homepage:mySkills' %}">
				<button class="btn" id="skills">Skills</button>
			</a>
		</div>
	</div>
	
	<!--My Projects. Section-->
	<div class="container-xl" style="overflow-x:hidden; padding:0; margin-top:0;">
		<div class="col-sm-6 section" style="background-color:#FFBBBB;">
			<h1 class="SectionHeading" style="padding-top:0;">MY PROJECTS.</h1>
			<p id="SectionText1" style="padding-left:3vw;">
				If you’are a fellow computer science student <br>
				and are interested in some of my project, here is <br>
				where you can find the links to the gitlab repository <br>
				of some my projects.
			</p>
			<a href="{% url 'homepage:myProjects' %}">
				<button class="btn" id="projects">Projects</button>
			</a>
		</div>
		<div class="col-sm-6 section" style="background-color:#000000;">
			<img src="{% static 'my projects 2.png' %}" class="icon" alt="projects">
		</div>
	</div>

	<!-- The Modal -->
	<div class="modal" id="myModal">
		<div class="modal-dialog">
			<div class="modal-content">
		  
				<!-- Modal Header -->
				<div class="modal-header">
					<h4 class="modal-title">KEKW</h4>
					<button type="button" class="close" data-dismiss="modal">&times;</button>
				</div>
			
				<!-- Modal body -->
				<div class="modal-body">
					<img src="{% static 'kekw.png' %}">
					<img src="{% static 'kekw.png' %}">
					<img src="{% static 'kekw.png' %}">
					<img src="{% static 'kekw.png' %}">
					<img src="{% static 'kekw.png' %}">
					<img src="{% static 'kekw.png' %}">
					<img src="{% static 'kekw.png' %}">
					<img src="{% static 'kekw.png' %}">
					<img src="{% static 'kekw.png' %}">
					<img src="{% static 'kekw.png' %}">
					<img src="{% static 'kekw.png' %}">
					<img src="{% static 'kekw.png' %}">
				</div>
			
				<!-- Modal footer -->
				<div class="modal-footer">
					<button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
				</div>
			</div>
		</div>
	</div>
	
	<!--Footer-->
	<nav class="navbar navbar-default" style="width:100%; margin-bottom:0px ;border: 0px;">
		<div class="container-fluid" id="footer">
			
			<a class="navbar-brand logo" href="#">Yafia.</a>
			
			<div class="collapse navbar-collapse" id="myNavbar">
				<ul class="nav navbar-nav">
					<li class="nav-btn"><a href="{% url 'homepage:home' %}">Home</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:aboutMe' %}">Profile</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:mySkills' %}">Skills</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:myProjects' %}">Projects</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:testform' %}">Form</a></li>
					<li class="nav-btn"><a href="{% url 'homepage:myfriend' %}">My Friends</a></li>
				</ul>
			</div>
		</div>
	</nav>
	
	<!--Challenge-->
	{% include 'copyright.html' %}
</body>
</html>